# Generated by Django 5.1.7 on 2025-05-20 13:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0002_remove_post_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='tag',
            field=models.ManyToManyField(blank=True, to='posts.tags', verbose_name='tags'),
        ),
    ]
