# Generated by Django 5.1.7 on 2025-05-13 11:28

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0006_alter_codesverification_changepasswordcode'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='rol',
        ),
        migrations.RenameField(
            model_name='customuser',
            old_name='status',
            new_name='is_checked',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='code_employee',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='date_start',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='ine',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='nss',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='rfc',
        ),
        migrations.AddField(
            model_name='customuser',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='customuser',
            name='house_number',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='customuser',
            name='phone',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='customuser',
            name='profile_photo',
            field=models.ImageField(blank=True, null=True, upload_to='profile_photos'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='street',
            field=models.TextField(blank=True, max_length=100, null=True, verbose_name='Street'),
        ),
        migrations.CreateModel(
            name='Reset_password',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token', models.CharField(max_length=10, unique=True)),
                ('expired_at', models.DateTimeField()),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.DeleteModel(
            name='Roles',
        ),
    ]
