# Generated by Django 5.1.7 on 2025-05-24 14:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0010_alter_customuser_following_delete_follow'),
    ]

    operations = [
        migrations.AddField(
            model_name='codesverification',
            name='is_used',
            field=models.BooleanField(default=False),
        ),
    ]
